language: node_js
node_js:
# - '15' # temporarily disabled because of npm@7 bug https://github.com/npm/cli/issues/1865
  - '14.15'
  - '12.13'
  - '10.13'
# - '8.16' # TODO: remove from `core-js@4`
os:
  - windows
  - linux
  - osx

sudo: false
